version: '3'
services:
  meli-backend-app:
    container_name: meli-backend-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - ./docker/app/.env # Read environment variables for docker
    ports: 
      - 8080:8080 # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - meli-backend-mysql
    networks:
      - meli-backend-magneto

  meli-backend-mysql:
    container_name: meli-backend-mysql
    env_file:
      - ./docker/app/.env # Read environment variables for docker
    image: mysql:8.0
    ports: 
      - 33061:3306 # Use port 33060 to avoid conflict with running mysql-server
    environment: 
      - MYSQL_ROOT_HOST=${DATABASE_HOST} 
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db_mysql:/var/lib/mysql
    command: --innodb-use-native-aio=0
    networks:
      - meli-backend-magneto

# Networks to be created to facilitate communication between containers
volumes: 
  api:
  db_mysql:
  
networks:
  meli-backend-magneto:
    driver: bridge

  